### ISSUE TITLE
Upgrade GKE to latest stable version

### ISSUE THREAD

**Issue by victortrac** [etcd-io/discovery.etcd.io#11]
It'd be nice to upgrade the GKE cluster to the latest stable version of k8s to take advantage of new GKE features like VPC aliasing, workload identity, regional masters, private API endpoint, and to get the latest security updates.

**Comment by eduartua** [comment]
Prod and dev cluster are using a newer k8s version. See [here](https://github.com/etcd-io/discovery.etcd.io/commit/49b6ae982fe50367e1c774a621a5365060a26c01).
