### ISSUE TITLE
Implement Cloud Build for CI/CD

### ISSUE THREAD

**Issue by victortrac** [etcd-io/discovery.etcd.io#12]
Once https://github.com/etcd-io/etcd/pull/10627 is merged and #9 is finished, we should implement Cloud Build to automatically build and deploy discoveryserver to the dev environment.

**Comment by eduartua** [comment]
@philips we suggest placing the discoveryserver code in a separate repository,  as it would allow us to create the cloudbuild pipeline desired.

**Comment by eduartua** [comment]
@philips I'm going to explore the repository and see how we can isolate the discovery server go code. Do you think this is a good approach to implement the cloudbuild pipeline?

**Comment by philips** [comment]
Cloudbuild is probably fine. Quay was working fine too.

**Comment by eduartua** [comment]
Cloudbuild has been implemented, see [commit](https://github.com/etcd-io/discoveryserver/commit/803687417c3e5f22cb2cbaa1d985b47d6299c1a0). Closing this.
