### ISSUE TITLE
production burn down

### ISSUE THREAD

**Issue by philips** [etcd-io/discovery.etcd.io#2]
This is a list of things that need to happen to ensure long term production stability:

- [x] Rollout branch with token garbage collection
- [x] Hook-up https://discovery.etcd.io/health to pingdom, etc
- [ ] Configure and deploy S3 backups (xref #1)
- [ ] Automatic building of container

**Comment by victortrac** [comment]
@philips I created issues #12 and #13, which should take care of your last two checkboxes (in addition to other enhancements I think we can make).  Feel free to close this issue if you agree.

**Comment by philips** [comment]
looks good.
