### ISSUE TITLE
CNCF Handoff

### ISSUE THREAD

**Issue by philips** [etcd-io/discovery.etcd.io#3]
- [ ] Add CNCF on-call to stackdriver discovery.etcd.io/health alert
- [ ] Ensure CNCF has access to the GKE cluster and stackdriver
- [ ] Answer any questions about the architecture
- [ ] Create an SLO on upgrades

**Comment by philips** [comment]
![discovery etcd io architecture](https://user-images.githubusercontent.com/33544/56688334-512f7f80-668d-11e9-8dda-a2b92f4b7030.png)

**Comment by idvoretskyi** [comment]
@philips can you please assign this to me?

**Comment by philips** [comment]
@idvoretskyi you need to accept org invite.

**Comment by idvoretskyi** [comment]
@philips done, thanks.

**Comment by philips** [comment]
assigned.

**Comment by idvoretskyi** [comment]
@philips am I right that we may close this?

**Comment by philips** [comment]
yes, tahnk you
