### ISSUE TITLE
https://discovery.etcd.io/new?size=3 gives back http url

### ISSUE THREAD

**Issue by mattlqx** [etcd-io/discovery.etcd.io#31]
At some point recently, it appears discovery.etcd.io has started giving back http urls instead of https urls when requesting a new token url for discovery. The http url gives a 308 back to https when used so I'm guessing this was not intentional.

**Comment by eduartua** [comment]
The problem is the value of this [DISC_HOST URL](https://github.com/etcd-io/discovery.etcd.io/blob/master/kubernetes/helm/discoveryserver/prod.values.yaml#L27).
This [PR](https://github.com/etcd-io/discovery.etcd.io/pull/32) fixes the issue.

**Comment by victortrac** [comment]
#32 deployed. 

@mattlqx thanks for the bug report.
