### ISSUE TITLE
discovery.etcd.io is down (for maintenance)

### ISSUE THREAD

**Issue by strigazi** [etcd-io/discovery.etcd.io#51]
The services is unavailable since: https://grafana.prod.discovery.etcd.io/d/uiLwPyPWk/discoveryserver?orgId=1&from=1640079655667&to=1640092338476&var-instance=10.128.0.37:9100

```
$ curl https://discovery.etcd.io
<html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx/1.17.7</center>
</body>
</html>
```

**Comment by strigazi** [comment]
Hello @philips and @victortrac ,

I'm @ you since you are one the people that have closed related issues in the repository.

Cheers,
Spyros

**Comment by victortrac** [comment]
@strigazi We're currently doing maintenance on it (upgrading all major components).

**Comment by rochaporto** [comment]
@victortrac thanks for the info. Do you know how long this will take? Just to have an idea.

**Comment by victortrac** [comment]
It's back online now. Apologies for the extended maintenance.

**Comment by strigazi** [comment]
Thank you for the promt reply!

**Comment by rochaporto** [comment]
Thanks @victortrac !

**Comment by victortrac** [comment]
Just ran into another issue. Should be resolved in 15 minutes.

**Comment by victortrac** [comment]
Ran into an issue with auth on the discovery server and the bitnami etcd helm chart, but it's resolved now. Logs and graphs look good now: 

https://grafana.prod.discovery.etcd.io/d/uiLwPyPWk/discoveryserver?orgId=1&from=now-5m&to=now&var-instance=10.128.0.42:9100

Please re-open if there are any issues!
