### ISSUE TITLE
Default TTL of token?

### ISSUE THREAD

**Issue by openstacker** [etcd-io/discovery.etcd.io#6]
@philips @idvoretskyi Could you please let me know the expiry time of a token? Since I'm trying to document it in OpenStack Magnum so that we can rely on this service with much confidence. Thank you.

**Comment by philips** [comment]
12 hours https://github.com/etcd-io/discovery.etcd.io/blob/master/discoveryserver.yaml#L37

**Comment by philips** [comment]
I am willing to expand this to longer. I set it at 12 hours because it seems that if a cluster is not fully up after 12 hours something has gone really wrong.

**Comment by openstacker** [comment]
@philips Thanks for answering my question. I agree with you, 12hours should be enough. I asked because it was much longer than that, do you know the old number? I think it was several days

**Comment by philips** [comment]
The old number was upwards of months because we had no automated garbage collection. [Until the rewrite](https://groups.google.com/forum/?hl=en#!topic/etcd-dev/q-pN4PiGY_o) that was deployed last month there was just a script that we ran when things got "too big".
