### ISSUE TITLE
Access for sig-k8s-infra-leads to `etcd-io-dev` and `etcd-io` gcp projects

### ISSUE THREAD

**Issue by jmhbnz** [etcd-io/discovery.etcd.io#79]
Following the creation of `sig-etcd` and in advance of upcoming pricing changes for google workspaces the etcd project are aiming to move existing gcp projects we own under the kubernetes shared GCP org to reduce costs and improve the oversight and management of these projects.

Refer:
- https://github.com/kubernetes/k8s.io/pull/6542
- https://github.com/kubernetes/community/issues/7739

The initial stage of this requires us to add `sig-k8s-infra-leads@kubernetes.io` to the gcp projects with the `Owner` role so they can assess resource usage and confirm we can proceed absorbing these under the kubernetes org.

This has been completed for `etcd-development` however as per the terraform modules in this repository we also have projects `etcd-io-dev` and `etcd-io` which we don't seem to have access to in order to be able to grant access.

@victortrac can you please confirm if these projects are still in use? If so can you please grant access as described above?

Any questions please feel free to ping me on kubernetes slack :pray:

**Comment by jmhbnz** [comment]
Gentle ping @victortrac, @eduartua

**Comment by victortrac** [comment]
Hey @jmhbnz - `etcd-io` is in use and hosts the GKE cluster behind discovery.etcd.io.

However, it doesn't look like these GCP projects allow us to add external groups as Owners:
![image](https://github.com/etcd-io/discovery.etcd.io/assets/85194/57d251d6-2434-4cba-a5d7-af8389617dcc)

 Seems like adding `sig-k8s-infra-leads@kubernetes.io` as an Editor be sufficient for auditing purposes, no?

**Comment by jmhbnz** [comment]
Thanks @victortrac - No problem this was the same with the `etcd-dev` main gcp project. Please grant Editor + IAM Admin (the latter will be used to facilitate moving the project if costs are accepted under k8s community infra).

**Comment by victortrac** [comment]
@jmhbnz Done for both `etcd-io` and `etcd-io-dev`. Please reopen if you need anything else!

**Comment by jmhbnz** [comment]
Confirming today both `etcd-io` and `etcd-io-dev` projects were moved from the Linux Foundation org to the Kubernetes org and billing account updated from CNCF to Kubernetes project.

This should not cause any issues, if something does come up please ping me on k8s slack, thanks.
