### ISSUE TITLE
Backport VPC and GKE to terraform

### ISSUE THREAD

**Issue by victortrac** [etcd-io/discovery.etcd.io#8]
Currently the GCP environment that runs discovery.etcd.io is manually built. It'd be nice to turn it into infrastructure-as-code so that it becomes reproducible and have a change audit-log.

**Comment by eduartua** [comment]
Just to inform you that I'll be working on this issue.

**Comment by eduartua** [comment]
See the backport [here](https://github.com/etcd-io/discovery.etcd.io/commit/25eb5a5a94295a77ee4c3a3bb1812feb093bc88f)
