### ISSUE TITLE
Create a dev/staging environment

### ISSUE THREAD

**Issue by victortrac** [etcd-io/discovery.etcd.io#9]
There's only a single environment for `discovery.etcd.io`, which means that there's not an environment to test upgrades to GKE, etcd, or the discovery service itself. Once #8 is done, we should use that template to generate a pre-prod environment to enable testing of changes to the service.

**Comment by eduartua** [comment]
Two environment were created, dev and prod. Cloudkite terraform modules were used, [see](https://github.com/cloudkite-io/terraform-modules). The actual implementation [here](https://github.com/etcd-io/discovery.etcd.io/commit/25eb5a5a94295a77ee4c3a3bb1812feb093bc88f).
